pipeline {
    agent {
        docker { image 'azul/zulu-openjdk:11' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}